name: Deploy to AWS-EBS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check secrets presence
        run: |
          test -n "${{ secrets.AWS_ACCESS_KEY_ID }}" && echo "ACCESS_KEY_PRESENT" || echo "ACCESS_KEY_MISSING"
          test -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" && echo "SECRET_KEY_PRESENT" || echo "SECRET_KEY_MISSING"

      - name: Zip application
        run: zip -r app.zip . -x "*.git*" "tmp/*" "log/*" ".DS_Store"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aqi-app
          environment_name: aqi-app-staging
          version_label: v-${{ github.sha }}
          region: eu-north-1
          deployment_package: app.zip
